version: "3.9"

services:
  server:
    build: ./server
    ports:
      - 1223:1223
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - 1224:1224
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
